variable "application_type" {}
variable "resource_type" {}
variable "location" {}
variable "resource_group" {}
variable "subnet_id" {}
variable "public_ip" {}
variable "vm_size" {}
variable "admin_username" {}
variable "admin_password" {}
